console.log("Forio frontend is connected successfully.");

const submitButton = document.getElementById("submit");
const resultsContainer = document.getElementById("results");

if(submitButton){
    submitButton.addEventListener("click", function () {
        let score = 0;
        let mistakes = [];

        const q1 = document.querySelector('input[name="question1"]:checked');
        const q2 = document.querySelector('input[name="question2"]:checked');
        const q3 = document.querySelector('input[name="question3"]');
        const q4 = document.querySelector('input[name="question4"]:checked');
        const q5 = document.querySelector('input[name="question5"]:checked');

        if (q1 && q1.value === "A") {
            score++;
        } else {
            mistakes.push("Question 1: Correct answer is A: One important preparation method is an incident response plan which summarises the steps staff should follow during a cyber incident.");

        }

         if (q2 && q2.value === "False") {
            score++;
        } else {
            mistakes.push("Question 2: Correct answer is False: Staff training is important as it helps reduce mistakes that could damage evidence, as well as helping employees understand how to recognise and report suspicious activity.");
        }

         if (q3 && q3.value === "Risk assessment") {
            score++;
        } else {
            mistakes.push("Question 3: Correct answer is risk assessment: Risk assessments help organisations identify potential threats and vulnerabilities before an incident happens.");
        }

         if (q4 && q4.value === "D") {
            score++;
        } else {
            mistakes.push("Question 4: Correct answer is D: Logs are records that are generated by IT systems and track digital activities.");
        }

         if (q5 && q5.value === "False") {
            score++;
        } else {
            mistakes.push("Question 5: Correct answer is False: It is important that organsiations assign roles and responsibilities for each department in the event of an incident");
        }

         const quizResult = {
            username: localStorage.getItem("username"),
            quizName: "quiz2",
            score: score,
            total: 5,
            mistakes: mistakes
        };

         localStorage.setItem("quizResult", JSON.stringify(quizResult));

         fetch("http://localhost:3000/save-result", {
            method: "POST",
            headers: { "Content-Type": "application/json"},
            body:JSON.stringify(quizResult)
        });
    });
    
}

const savedResults = document.getElementById("saved-results");
const username = localStorage.getItem("username");

if (savedResults && username) {
    fetch(`http://localhost:3000/results/${username}/quiz2`)
        .then(response => response.json())
        .then(result => {
            if (result) {
                const mistakes = JSON.parse(result.mistakes);

                savedResults.innerHTML = `
                    <h2>Your result:</h2>
                    <p><strong>Score:</strong> ${result.score}/${result.total}</p>
                    <p><strong>Mistakes:</strong></p>
                    <p>${mistakes.length === 0 ? "No mistakes made." : mistakes.join("<br>")}</p>
                `;
            }
        });
}
